### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by joserobleda** [elastic-coders/github-project-story-points#1] opened 2016-11-13 21:44 UTC
Hi, I was looking for extension like this one, so thanks!

Have you uploaded this to the chrome store or to anywhere else so I can share it with my teammates easily?

**Comment by thenikso** [comment] 2016-11-17 11:50
gosh I've never ended the publish process. for the time being you can:
1. download and extract the [latest zip of this plugin](https://github.com/elastic-coders/github-project-story-points/archive/master.zip)
2. go to `chrome://extensions/` on your chrome
3. click on `Load unpacked extension...` and select the extracted plugin folder

is this working for you?

**Comment by joserobleda** [comment] 2016-11-18 18:44
I can install it with no problems, but it doesn't seems to work... any advice?

**Comment by acoven** [comment] 2016-11-24 07:39
@thenikso Thanks for a great project! I've found what I think the problem is that @joserobleda is reporting. I'll create a new issue. (Or I can fix it and give you a pull request, but I suspect you'll fix it a lot faster with me giving you the change to incorporate.)

**Comment by acoven** [comment] 2016-11-26 09:12
@thenikso Yup, found it, and combined that bug fix with a few other things. Question: Where is the CSS defined that is handling the formatting for class "github-project-story-points"? I can't find it anywhere and would like to introduce another design for spent points that's square and a different color. #4

**Comment by acoven** [comment] 2016-12-14 00:56
Fixed with #4

**Closed as completed by acoven** 2016-12-14 00:56 UTC
